service: sls-project
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x


plugins:
  - serverless-offline

functions:
  indexPlanets:
    handler: index.allPlanets
    events:
      - http: 
          path: planetas
          method: GET
  showPlanet:
    handler: index.showPlanet
    events:
      - http: 
          path: planetas/{id}
          method: GET