service: sls-project
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  environment:
    DB_HOST: ${file(database.json):database_host}
    DB_USER: ${file(database.json):database_user}
    DB_PASSWORD: ${file(database.json):database_password}
    DB_PORT: ${file(database.json):database_port}
    DB_NAME: ${file(database.json):database_name}
  iam:
    role:
      statements:
      - Effect: "Allow"
        Action:
          - "rds:DescribeDBInstances"
          - "rds:Connect"
        Resource: "*"

plugins:
  - serverless-offline

functions:
  listPlanets:
    handler: index.listPlanets
    events:
      - http: 
          path: planetas
          method: GET
  showPlanet:
    handler: index.showPlanet
    events:
      - http: 
          path: planetas/{id}
          method: GET
  listBooks:
    handler: index.listBooks
    events:
      - http:
          path: libros
          method: GET
  createBook:
    handler: index.createBook
    events:
      - http:
          path: libros
          method: POST
  makeMigrations:
    handler: index.makeMigrations
    timeout: 30

custom:
  scriptHooks:
    after:deploy:deploy: sls invoke -f makeMigrations