service: sls-project
frameworkVersion: '3'

provider:
  name: aws
  stage: ${opt:stage, 'dev'}
  runtime: nodejs18.x
  environment:
    DB_HOST: ${file(database.json):database_host}
    DB_USER: ${file(database.json):database_user}
    DB_PASSWORD: ${file(database.json):database_password}
    DB_PORT: ${file(database.json):database_port}
    DB_NAME: ${file(database.json):database_name}

plugins:
  - serverless-offline

functions:
  listPlanets:
    handler: index.listPlanets
    events:
      - http: 
          path: planetas
          method: GET
  showPlanet:
    handler: index.showPlanet
    events:
      - http: 
          path: planetas/{id}
          method: GET
  listUsers:
    handler: index.listUsers
    events:
      - http:
          path: usuarios
          method: GET
  createUser:
    handler: index.createUser
    events:
      - http:
          path: usuarios
          method: POST