service: sls-project
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x

plugins:
  - serverless-offline

functions:
  index:
    handler: index.handler
    events:
      - http: 
          path: test
          method: GET