service: sls-project
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  iam:
    role:
      statements:
      - Effect: "Allow"
        Action:
          - dynamodb:*
        Resource: "*"

plugins:
  - serverless-offline

functions:
  listPlanets:
    handler: index.listPlanets
    events:
      - http: 
          path: planetas
          method: GET
  showPlanet:
    handler: index.showPlanet
    events:
      - http: 
          path: planetas/{id}
          method: GET
  listBooks:
    handler: index.listBooks
    timeout: 30
    events:
      - http:
          path: libros
          method: GET
  createBook:
    handler: index.createBook
    timeout: 30
    events:
      - http:
          path: libros
          method: POST
resources:
  Resources:
    BooksTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: BooksTable
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH

